language: csharp

before_install:
  - nuget restore MaxMind.MinFraud.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild /p:TargetFrameworkVersion="v4.5"
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MaxMind.MinFraud.UnitTest/bin/Debug/MaxMind.MinFraud.UnitTest.dll

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
