language: csharp

before_install:
  - nuget restore MaxMind.MinFraud.sln
  - nuget install NUnit.Console -Version 3.0.0

script:
  - xbuild /p:TargetFrameworkVersion="v4.5"
  - mono ./NUnit.Console.3.0.0/tools/nunit3-console.exe ./MaxMind.MinFraud.UnitTest/bin/Debug/MaxMind.MinFraud.UnitTest.dll

sudo: false

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
