version: 1.0.{build}

os: Visual Studio 2015 RC

before_build:
  - nuget restore

install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

build:
  verbosity: minimal

notifications:
- provider: HipChat
  room: dev
  auth_token:
    secure: NtKXu/kGk8Td4YqCH95camAcNQtB3rMll+5DALAmbDY=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
