---
version: '1.0.{build}'

os: Visual Studio 2019

environment:
  global:
    MAXMIND_TEST_BASE_DIR: $(APPVEYOR_BUILD_FOLDER)/MaxMind.MinFraud.UnitTest
  matrix:
    - CONFIGURATION: Debug
      CONSOLE_FRAMEWORK: net45
      LIB_FRAMEWORK: net45
      TEST_FRAMEWORK: net452
    - CONFIGURATION: Release
      CONSOLE_FRAMEWORK: net45
      TEST_FRAMEWORK: net452
      LIB_FRAMEWORK: net45
    - CONFIGURATION: Debug
      CONSOLE_FRAMEWORK: netcoreapp3.0
      LIB_FRAMEWORK: netstandard1.4
      TEST_FRAMEWORK: netcoreapp3.0
    - CONFIGURATION: Release
      CONSOLE_FRAMEWORK: netcoreapp3.0
      LIB_FRAMEWORK: netstandard1.4
      TEST_FRAMEWORK: netcoreapp3.0
    - CONFIGURATION: Debug
      CONSOLE_FRAMEWORK: netcoreapp3.0
      LIB_FRAMEWORK: netstandard2.0
      TEST_FRAMEWORK: netcoreapp3.0
    - CONFIGURATION: Release
      CONSOLE_FRAMEWORK: netcoreapp3.0
      LIB_FRAMEWORK: netstandard2.0
      TEST_FRAMEWORK: netcoreapp3.0

before_build:
  - git submodule update --init --recursive

build_script:
  - ps: |
      if (gcm dotnet -errorAction SilentlyContinue) {
        echo "Using dotnet '$((gcm dotnet).Path)'"
        dotnet --info
      }
      else {
        echo "dotnet.exe not found"
        exit 1
      }

      # Restore Packages
      dotnet restore MaxMind.MinFraud.sln

      # Build Projects
      dotnet build -c $env:CONFIGURATION -f $env:LIB_FRAMEWORK MaxMind.MinFraud\MaxMind.MinFraud.csproj
      dotnet build -c $env:CONFIGURATION -f $env:TEST_FRAMEWORK MaxMind.MinFraud.UnitTest\MaxMind.MinFraud.UnitTest.csproj

test_script:
  # Run Unit Tests
  - dotnet test -f %TEST_FRAMEWORK% -c %CONFIGURATION% MaxMind.MinFraud.UnitTest\MaxMind.MinFraud.UnitTest.csproj

after_test:
  # Run Unit Tests
  - dotnet pack -c %CONFIGURATION% MaxMind.MinFraud\MaxMind.MinFraud.csproj

artifacts:
  - path: 'MaxMind.MinFraud\bin\**\*.nupkg'

notifications:
  - incoming_webhook:
      secure: 8FZP/RE3nS77Yi5UWOB/DQKCRSJxh/BYrLjVPEAkBG6mRojCz3r2mnla4O/5GwzDr7V6XCpxCP0xo1buCcZRIzRN0ZUWJ5hzEQqW5u7R+vM=
    channel: ci
    on_build_failure: true
    on_build_status_changed: true
    on_build_success: true
    provider: Slack
  - on_build_failure: true
    on_build_status_changed: true
    on_build_success: false
    provider: Email
    subject: 'AppVeyor build {{status}}'
    to:
      - dev-ci@maxmind.com
