name: Run tests
on:
  push:
  pull_request:
  schedule:
    - cron: '3 20 * * SUN'

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    name: Dotnet on ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup dotnet 2.2
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2

      - name: Setup dotnet 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.*

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*

      - name: Build
        run: |
              dotnet build MaxMind.MinFraud
              dotnet build MaxMind.MinFraud.UnitTest

      - name: Run tests
        run: dotnet test MaxMind.MinFraud.UnitTest/MaxMind.MinFraud.UnitTest.csproj
